version: '2'
services:
    fmp-app:
        image: fmp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://fmp-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=fmp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    fmp-mongodb:
        extends:
            file: mongodb.yml
            service: fmp-mongodb
